server:
  port: 6677
spring:
  redis:
    cluster:
      #所有集群节点
      nodes: 192.168.32.101:6379,192.168.32.102:6379,192.168.32.103:6379,192.168.32.104:6379,192.168.32.105:6379,192.168.32.106:6379
    maxIdle: 15
    maxWaitMillis: 2000
    maxTotal: 50
    testOnBorrow: true
    testOnReturn: true
    timeout: 5000
  application:
    name: redis-cluster
eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #单机版
      defaultZone: http://localhost:7001/eureka