server:
  port: 8088

spring:
  application:
    name: mybatis-plus8088
  cloud:
  #Config客户端配置
    config:
      label: dev #分支名称
      name: config #配置文件名称
      profile: dev #读取后缀名称   上述3个综合：master分支上config-dev.yml的配置文件被读取http://config-3344.com:3344/master/config-dev.yml

eureka:
  client:
      #表示是否将自己注册进EurekaServer默认为true。
      register-with-eureka: true
      #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
      fetchRegistry: true
      service-url:
        #单机版
        defaultZone: http://localhost:7001/eureka
        #集群版
#        defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: mybatis-plus8088
    prefer-ip-address: true

# Logger Config
logging:
  level:
    com.learn.demo.mapper: debug

