server:
  port: 5566
spring:
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.100.104:26379
    jedis:
      pool:
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10