spring:
  redis:
    sentinel:
      master: mymaster
    jedis:
      pool:
#        max-active: 1024
#        max-wait: 20000
#        max-idle: 200
#        min-idle: 10
        #最大连接数
        max-active: 1024
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 20000
        #最大空闲
        max-idle: 200
        #最小空闲
        min-idle: 10
myredis:
 sentinel:
  host: 192.168.30.84
  port: 26379

#spring:
#  redis:
#    host: 192.168.30.81
#    port: 6379
#    database: 0